= Warning/Preface

*Warning:* this is a repository I haven't _seriously_ touched since October, 2014. I recently updated it with better documentation, some fixes, just because some friends of mine were interested in it, and heck, it looks good on a resume.

That's not to say I'm not interested in hearing what you have to say! Please, drop me an e-mail if you have any comments! My email is lillian.lynn.lemmer@gmail.com. Though, I don't plan on adding any new features or continuing the development of Formhandler in any serious manner.

This software was more so created as an experiment, to flex my brain and learn some things.

= formhandler: automatically fulfill the job of a frontend developer for simple tasks

In a couple of commands, in one CGI script, use a function to:

1. Provide an HTML form interface for that function.
2. Provide the HTML-ified evaluation of sending corresponding POST/GET fields to aforementioned function(s).

Includes tools for automatically converting data returned from a function, to HTML, e.g., dict > html, list > html, etc.

I was tired of making and updating  web interfaces to various scripts I've written at work. Various people use various scripts through super simple CGI scripts.

== Compatibility

Tested functional with Python 2.7.6 and Python 3.4.

Automate the development of a web/CGI script interface to a function.

== Deploy and Test

1. python setup.py install
2. Launch testhttpd.py. This acts as a temporary testing web server. It should launch http://localhost:8080/ in a new web browser tab.
3. Open test.py in a file editor to see what's going on!

Note: you may need to +chmod +X+ the proper cgi scripts. I also may need to change file headers to #!/usr/bin/python. You need to create the uploads and resources directory for the demo. Just make demo directory.

== Developing with Formhandler

I strongly recommend taking a look at +examples/test.py+. The example comes with +examples/testhttpd.py+ which enables you to start a debugging HTTP CGI server to interact with test.py.

You're supposed to install Formhandler as a package. It should not be in your public directory.

Formhandler uses introspection to extrapolate any assumptions it can make, e.g., it is able to extrapolate the function name and its argument names through this method.

You also have to do a little manual specification when formhandler is too stupid to assume any context, such as tell it that certain arguments are supposed to be files/a file field.

