= Warning/Preface

*Warning:* this is a repository I haven't _seriously_ touched since October, 2014. I recently updated it with better documentation, some fixes, just because some friends of mine were interested in it, and heck, it looks good on a resume.

That's not to say I'm not interested in hearing what you have to say! Please, drop me an e-mail if you have any comments! My email is lillian.lynn.lemmer@gmail.com. Though, I don't plan on adding any new features or continuing the development of FormHandler in any serious manner.

This software was more so created as an experiment, to flex my brain and learn some things.

= Purpose

Automatically fulfill the job of a frontend developer for simple tasks.

In a couple of commands, in one CGI script, use a function to:

1. Provide an HTML form interface for that function.
2. Provide the HTML-ified evaluation of sending corresponding POST/GET fields to aforementioned function(s).

Includes tools for automatically converting data returned from a function, to HTML, e.g., dict > html, list > html, etc.

I was tired of making and updating  web interfaces to various scripts I've written at work. Various people use various scripts through super simple CGI scripts.

Automate the development of a web/CGI script interface to a function.

== Compatibility

Tested functional with Python 2.7.6 and Python 3.4.

Like all of my software, this is chiefly tested, built in FreeBSD.

== Quickstart; Example

First, install all of the dependencies for Python:

----
$ sudo pip install -r requirements.txt
----

Then run the package installer:

----
$ sudo python setup.py install
----

Now that FormHandler is installed, we can try out the stuff in the example
directory. Change to the +example/+ directory and list its contents:

----
$ cd example
$ ls
resources    test.py      testhttpd.py tpl
----

First note that this is the web root of the +testhttpd.py+ test/debug web
server. So +test.py+ will be available through +http://localhost:8080/test.py+
(presuming your currend directory is +example/+).

resources::
  This directory contains static resources, e.g., CSS, which are available via
+http://localhost/resources/*+.
test.py::
  This is an example FormHandler CGI script, It's really the main focus of the
example. It shows you how to utilize FormHandler, from a developer perspective.
testhttpd.py::
  You run this to serve the current directory via a debug HTTP/CGI server. This
makes available +http://localhost:8080/test.py+ as well as other files in the
current directory and its descendants.
tpl::
  Oft-repeated HTML macros, e.g., header, footer. Parsed with the FormHandler's
template engine. Like a spiffier PHP include.
  
I recommend viewing +test.py+ in an editor to see how to develop with
FormHandler.

Don't forget to first mark +test.py+ as executable:

----
$ chmod +x test.py
----

When you run the debugging/demo web server:

----
$ python testhttpd.py
----

...it should open the correct URI to +test.py+ for you in a new web browser tab.

You may need to change file headers (#!/usr/bin/python).

You need to create the uploads and resources directory for the demo. Just make demo directory.

== Additional Notes

You're supposed to install FormHandler as a package. It should not be in your public directory.

FormHandler uses introspection to extrapolate any assumptions it can make, e.g., it is able to extrapolate the function name and its argument names through this method.

You have to do a little manual specification when FormHandler is too stupid to assume any context, such as tell it that certain arguments are supposed to be files/a file field.

